services:
  app:
    build:
      context: .
      dockerfile: ${DOCKER_DIR}/php-fpm/Dockerfile
    container_name: php-fpm
    volumes:
      - ${SOURCE_DIR}/:/${DOMAIN}
    expose:
      - ${PHP_APP_PORT}
      - ${PHP_DEBUG_PORT}
  web:
    build:
      context: .
      dockerfile: ${DOCKER_DIR}/nginx/Dockerfile
    container_name: nginx
    depends_on:
      - app
    ports:
      - ${WEB_PORT}:80
    volumes:
      - ${SOURCE_DIR}/:/${DOMAIN}
